fix: print error message on stderr instead of stdout

diff --git a/recipes/mender/files/rugpi-image b/recipes/mender/files/rugpi-image
--- a/recipes/mender/files/rugpi-image
+++ b/recipes/mender/files/rugpi-image
@@ -20,7 +20,7 @@ case "$STATE" in
         default_group=$(rugix-ctrl system info --json | jq -r '.boot.defaultGroup')
         active_group=$(rugix-ctrl system info --json | jq -r '.boot.activeGroup')
         if [ "${default_group}" == "${active_group}" ]; then
-            echo "Error: Active boot group is also the default boot group."
+            echo "Error: Active boot group is also the default boot group." >&2
             exit 1;
         fi
         ;;
